### ISSUE TITLE
Needs a way to load memory...

### ISSUE THREAD

**Issue by WestfW** [krakenlake/vmon#1]
If there was a way to deposit values in memory (even if just hex into RAM), you could use this monitor to load small programs onto your RISC-V device.  (this was occasionally used to load code on the original IBMPC using the "debug" utility.  You could load hex into RAM and save a .com file.)

I suggest accepting Intel Hex format lines, which would make the "command" be ":", provides some error checking, and is compatible with the output of many compiler tools.
There's some simple C code that does this here: https://github.com/WestfW/Duino-hacks/blob/master/hvTiny28prog/simpleParser.cpp#L271  (I don't think I'm currently up to converting this to RISC-V asm.)

(Extra credit if you can make an assembler, using the same instruction names already present in the disassembler.)

**Comment by krakenlake** [comment]
Yes, writing to memory and adding an assembler is on my list.

**Comment by krakenlake** [comment]
Meanwhile I added the "c" command to copy memory areas and the "p" command ("poke") to manually write byte values to memory, so getting stuff into memory is kind of covered on a basic level now. Advanced stuff is on the list as separate items now.
